### PR TITLE
Fixes #113 - Expose synchronization strategy constants.

### LINKED ISSUE #113: Expose Collection.strategy.*
Maybe I'm looking in the wrong place, but I can't see how I can access the Collection.strategy.* constants from outside the library (I am currently working around this by using the literal strings from https://github.com/Kinto/kinto.js/blob/master/src/collection.js#L85-L87).

### PR DESCRIPTION
**Pull request by n1k0**
Refs #113 and preparation patch for #150. r=? @leplatrem @michielbdejong

### CODE REVIEW

File: test/index_test.js [hunk 1]
```diff
@@ -64,6 +65,12 @@ describe("Kinto", () => {
         expect(Kinto.transformers.RemoteTransformer).to.eql(RemoteTransformer);
       });
     });
+
+    describe("get syncSrategy()", () => {
+      it("should provide an transformers static getter", () => {
```
Comment (michielbdejong) [inline test/index_test.js]: Typo "syncSrategy" -> "syncStrategy" (one line up) and "an transformers" -> "a syncStrategy"

**Comment by michielbdejong** [comment]
Thanks for this! r+wc
