### PR TITLE
Fix skipped remote deletion (fixes #540)

### LINKED ISSUE #540: Failed to execute 'delete' on 'IDBObjectStore' exception while syncing
I'm used to have this exception on Chrome for Android, it took me a while to debug that via remote devtools.
I'm not sure it has anything to do with Chrome or android, I imagine it has to do with the state that exists on the device.

I traced this exception back to this code:
https://github.com/Kinto/kinto.js/blob/3630426125a04650069f87d2461a8dc62fc2a82a/src/collection.js#L928
```
 transaction.delete(record.id);
```
Here, record.id is undefined.  record is just `{ deleted: true }`.

### PR DESCRIPTION
**Pull request by leplatrem**
This pull-request relies on kinto-http.js 2.5.1 

The `skipped` attribute in sync result now contains the record id that was skipped instead of a plain 404 error response body.

An integration test now executes a skipped remote deletion.

@n1k0 r?

### CODE REVIEW

File: test/integration_test.js [hunk 1]
```diff
@@ -809,50 +809,87 @@ describe("Integration tests", function() {
 
       });
 
+
```
Comment (n1k0) [inline test/integration_test.js]: Nit: A single line is enough

File: test/collection_test.js [hunk 2]
```diff
@@ -2059,7 +2059,10 @@ describe("Collection", () => {
         published: [],
         errors:    [],
         conflicts: [],
-        skipped:   [{data: {id: records[0].id}}]
+        skipped:   [{
+          id: records[0].id,
+          error: {errno: 110, code: 404, error: "Not found"}
```
Comment (n1k0) [inline test/collection_test.js]: Nit: trailing comma

File: test/integration_test.js [hunk 3]
```diff
@@ -809,50 +809,87 @@ describe("Integration tests", function() {
...
+          it("should properly list the encountered conflict", () => {
+            expect(conflicts).to.have.length.of(1);
+          });
+
+          it("should list the proper type of conflict", () => {
+            expect(conflicts[0].type).eql("outgoing");
+          });
+
+          it("should have the expected conflicting local version", () => {
+            expect(conflicts[0].local).eql({});
```
Comment (n1k0) [inline test/integration_test.js]: Nit: could we have a more explicit local version definition here? Empty object is vague and may be false-positive prone methinks...

File: test/integration_test.js [hunk 4]
```diff
@@ -809,50 +809,87 @@ describe("Integration tests", function() {
...
+          });
+
+          it("should provide the record", () => {
+            expect(result.skipped[0])
+              .to.have.property("id").eql(id);
+          });
         });
       });
 
+
```
Comment (n1k0) [inline test/integration_test.js]: Nit: single empty line
